# Generated by Django 5.0.2 on 2024-02-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pennapps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="has_application",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="first_hackathon",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="application",
            name="phone_number",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="school_attending",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="short_answer_1",
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="short_answer_2",
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="student_birthday",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="student_major",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="application",
            name="student_year",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="team_member1",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="team_member2",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="team_member3",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
